DROP TABLE IF EXISTS Credentials;

CREATE TABLE Credentials (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserName VARCHAR(40) NOT NULL,
    Password VARCHAR(40) NOT NULL
);